channels:
        - bioconda
        - conda-forge
        - jmeppley
dependencies:
        - perl-bioperl
        - perl-parallel-forkmanager
        - blast
        - mcl
        - metagene-annotator
        - hmmer
        - muscle
        - snakemake
        - biopython
        - coreutils
